### ISSUE TITLE
class 'RuntimeError'

### ISSUE THREAD

**Issue by nichijou147** [HypoX64/DeepMosaics#15]
I run this in python 3.6.8 and 3.7.10. Got the following error. Do you know why?
Error Type: <class 'RuntimeError'>
Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 500, 360] to have 3 channels, but got 4 channels instead
<FrameSummary file deepmosaic.py, line 66 in <module>>
<FrameSummary file deepmosaic.py, line 40 in main>
<FrameSummary file cores\core.py, line 112 in cleanmosaic_img>
<FrameSummary file models\runmodel.py, line 73 in get_mosaic_position>
<FrameSummary file models\runmodel.py, line 13 in run_segment>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 236 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 122 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 111 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file site-packages\torch\nn\modules\conv.py, line 301 in forward>
Please press any key to exit.

**Comment by HypoX64** [comment]
Whether the image you input is *.png with a transparent channel?

**Comment by nichijou147** [comment]
The image I input does not have a transparent channel, but when I tried the other images it was fine.
