### ISSUE TITLE
Error Type: <class 'RuntimeError'>

### ISSUE THREAD

**Issue by TremblingFool** [HypoX64/DeepMosaics#17]
This problem occurs when running

segment parameters: 12.4M
netG parameters: 11.38M
Clean Mosaic: C:\Users\Feild\Desktop\微信图片_20200518111928.png
--------------------ERROR--------------------
Error Type: <class 'RuntimeError'>
Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 360, 2236] to have 3 channels, but got 4 channels instead
<FrameSummary file deepmosaic.py, line 66 in <module>>
<FrameSummary file deepmosaic.py, line 40 in main>
<FrameSummary file cores\core.py, line 112 in cleanmosaic_img>
<FrameSummary file models\runmodel.py, line 73 in get_mosaic_position>
<FrameSummary file models\runmodel.py, line 13 in run_segment>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 236 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 122 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file models\BiSeNet_model.py, line 111 in forward>
<FrameSummary file site-packages\torch\nn\modules\module.py, line 477 in __call__>
<FrameSummary file site-packages\torch\nn\modules\conv.py, line 301 in forward>
Please press any key to exit.

**Comment by HypoX64** [comment]
Your *.png image has 4 channels, but the network only support 3 channel images . I will slove this bug.
