### ISSUE TITLE
兄得，我觉得会不会有个小Bug如果用  semantic  segmentation 来做的话

### ISSUE THREAD

**Issue by heartInsert** [HypoX64/DeepMosaics#2]
Because  different  image  will  have  different   马赛克的算法，比如分厚码 中码  薄码 ，对不同的数据集效果会不一样啊

Cyclegan我觉得会不会好一点

**Comment by HypoX64** [comment]
其实我想过这个问题，所以针对每个不同的数据集我都会重新训练一个模型。然后训练时的打码方式也有好几种，厚薄随机，目前用的是pix2pix，有时间我会试一下cyclegan，哈哈。

**Comment by xsyhome** [comment]
兄弟，pix2pixHD的源代码输出的JPG，怎么改成PNG的？压缩的太厉害了

**Comment by xsyhome** [comment]
我用pix2pixHD好像成功了？？？10部片子可以成功8部了，下步准备再多准备些数据集，效果应该会更好

**Comment by HypoX64** [comment]
> 我用pix2pixHD好像成功了？？？10部片子可以成功8部了，下步准备再多准备些数据集，效果应该会更好
做数据集真的是头疼...年前有时间我会继续操作一波.

**Comment by heartInsert** [comment]
> 我用pix2pixHD好像成功了？？？10部片子可以成功8部了，下步准备再多准备些数据集，效果应该会更好

不是，你说的成功的10部片子是岛国的源片？还是你拿到高清后自己打的码？

**Comment by xsyhome** [comment]
就网上随便找的打码片啊，因为我设备有限，只有能跑512的，所以清晰度差了一点，粗略看起来已经跟无马片差不多了

**Comment by xsyhome** [comment]
> > 我用pix2pixHD好像成功了？？？10部片子可以成功8部了，下步准备再多准备些数据集，效果应该会更好
> 
> 不是，你说的成功的10部片子是岛国的源片？还是你拿到高清后自己打的码？

就网上随便找的打码片啊，因为我设备有限，只能跑512的，所以清晰度差了一点，粗略看起来已经跟无马片差不多了

**Comment by heartInsert** [comment]
@xsyhome  我靠， 效果这么好的吗，不行，我的2080ti在躁动，他在躁动你听到了吗？

**Comment by xsyhome** [comment]
你有

> @xsyhome 我靠， 效果这么好的吗，不行，我的显卡在躁动，他在躁动你听到了吗？

你有QQ吗？我加你，发个片段你看看

**Comment by xsyhome** [comment]
> @xsyhome 我靠， 效果这么好的吗，不行，我的显卡在躁动，他在躁动你听到了吗？
> 感谢AI，感谢科学
你有QQ吗？我加你，发个片段你看看

**Comment by heartInsert** [comment]
@xsyhome  361846570

**Comment by xsyhome** [comment]
> @xsyhome 361846570

加你了
