### ISSUE TITLE
i got error and i don't know why

### ISSUE THREAD

**Issue by skyzombie89** [HypoX64/DeepMosaics#22]
--------------------ERROR--------------------
Error Type: <class 'UnboundLocalError'>
local variable 'img_fake' referenced before assignment
<FrameSummary file deepmosaic.py, line 66 in <module>>
<FrameSummary file deepmosaic.py, line 45 in main>
<FrameSummary file D:\DeepMosaics-master\cores\core.py, line 142 in cleanmosaic_video_byframe>
Please press any key to exit.

i run the program on windows 10 with newest python and got this error.

i don't know how to fix it.

**Comment by HypoX64** [comment]
I'm not sure what happened.
You can try the new codes. And if it doesn't work again, please tell me your python and pytorch version.

**Comment by skyzombie89** [comment]
i fix it. it was compatibility issues between python and another python i download from conda. by the way i use gpu( my pc has 1070ti and 8600k) but it takes almost 48h to remove mosaic...... it is right? if this is your purpose you should add 
Multiprocessing

**Comment by HypoX64** [comment]
Yes,it don't support multiprocessing now. If your video is too long, please use --start_time and --last_time to cut out part of video to test.

**Comment by skyzombie89** [comment]
> Yes,it don't support multiprocessing now. If your video is too long, please use --start_time and --last_time to cut out part of video to test.

pls show me example of --start_time and --last_time. do i put 2h, 2:00:00 or something else?

**Comment by HypoX64** [comment]
https://github.com/HypoX64/DeepMosaics/blob/master/docs/options_introduction.md
