### ISSUE TITLE
Can't Detect Mosaic

### ISSUE THREAD

**Issue by BroNils** [HypoX64/DeepMosaics#24]
I just tested out on Google Colab with image sample on readme (white cloth girl), and result is still the same (blurred face)

```
Tested on: Google Colab
Runtime: GPU
Cuda: True
```

More information & screenshot [here](https://imgur.com/a/D5b9AcE)

**Comment by BroNils** [comment]
And also, for later updates, please allow spaces in the folder names. I can't access file to my google-drive folder because it contain space (/content/drive/My Drive)

**Comment by HypoX64** [comment]
I don't recommend using too small resolution image for testing.
Try this:
![e](https://user-images.githubusercontent.com/35624681/90387850-7d101900-e0b9-11ea-8cfb-21edf5c41769.jpg)

**Comment by BroNils** [comment]
Okay, I'll try it later.
Thanks for your reply

**Comment by BroNils** [comment]
It works, thank you so much !
