### ISSUE TITLE
48h for 1video?

### ISSUE THREAD

**Issue by skyzombie89** [HypoX64/DeepMosaics#25]
i use gpu( my pc has 1070ti and 8600k) but it takes almost 48h to remove mosaic...... 

is it right?

**Comment by HypoX64** [comment]
#22

**Comment by BroNils** [comment]
Use Google Colab, only took 4-8hour for 1hour video.

**Comment by skyzombie89** [comment]
> Use Google Colab, only took 4-8hour for 1hour video.

i faild to use colab. it didn't provide enough disk space. even i mount gsuite it still use colab disk space. pls tell me how to use colab

**Comment by skyzombie89** [comment]
> Use Google Colab, only took 4-8hour for 1hour video.

i just pay for colab pro to earn more disk space.... but i got "cannot connect to X server" error how did you solve it?

**Comment by BroNils** [comment]
> i faild to use colab. it didn't provide enough disk space. even i mount gsuite it still use colab disk space. pls tell me how to use colab

Use mine here, [Demo Colab](https://colab.research.google.com/drive/1iWdq2ZA6ov8r77XJ97J1rmQcvFn-Nv_p).
Don't process video in one phase for video with 2 hour duration or more, you can cut video to a short duration (e.g under 1 hour, like 40 minutes).

**Comment by BroNils** [comment]
> i just pay for colab pro to earn more disk space.... but i got "cannot connect to X server" error how did you solve it?
I use RDP with a little script for auto/anti reconnect (javascript), but your browser tab/window must on Google Colab for preventing idle.

**Comment by BroNils** [comment]
> Use mine here, [Demo Colab](https://colab.research.google.com/drive/1iWdq2ZA6ov8r77XJ97J1rmQcvFn-Nv_p).
> Don't process video in one phase for video with 2 hour duration or more, you can cut video to a short duration (e.g under 1 hour, like 40 minutes).

sorry for the language, you can translate it if you don't understand.

and sorry for late reply

**Comment by skyzombie89** [comment]
> > Use mine here, [Demo Colab](https://colab.research.google.com/drive/1iWdq2ZA6ov8r77XJ97J1rmQcvFn-Nv_p).
> > Don't process video in one phase for video with 2 hour duration or more, you can cut video to a short duration (e.g under 1 hour, like 40 minutes).
> 
> sorry for the language, you can translate it if you don't understand.
> 
> and sorry for late reply

thanks for your reply. 
but the x server problem is not a colab reconnect issue. 

i find answer in here. https://stackoverflow.com/questions/39840184/python-code-crashes-with-cannot-connect-to-x-server-when-detaching-sshtmux-se

the interest thing of your colab code is even you didn't use xvfb you hadn't get x sever crash....

anyway i will follow your manual and let's see it's working

**Comment by xinxin8816** [comment]
> > > Use mine here, [Demo Colab](https://colab.research.google.com/drive/1iWdq2ZA6ov8r77XJ97J1rmQcvFn-Nv_p).
> > > Don't process video in one phase for video with 2 hour duration or more, you can cut video to a short duration (e.g under 1 hour, like 40 minutes).
> > 
> > 
> > sorry for the language, you can translate it if you don't understand.
> > and sorry for late reply
> 
> thanks for your reply.
> but the x server problem is not a colab reconnect issue.
> 
> i find answer in here. https://stackoverflow.com/questions/39840184/python-code-crashes-with-cannot-connect-to-x-server-when-detaching-sshtmux-se
> 
> the interest thing of your colab code is even you didn't use xvfb you hadn't get x sever crash....
> 
> anyway i will follow your manual and let's see it's working

So easy, add '--no_preview'
