### ISSUE TITLE
老哥，能不能放几个预训练模型

### ISSUE THREAD

**Issue by FeverKing** [HypoX64/DeepMosaics#3]
如题，能否将预训练模型也上传

**Comment by HypoX64** [comment]
老版本的预训练模型有啊，在百度盘里，但是新版本的预训练模型还学校服务器...这得疫情结束了我才能拿到....

**Comment by 337529542** [comment]
预训练的方法再readme里面说一下吧，我这有vr的片源，不知道能用不
