### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by OneRain233** [HypoX64/DeepMosaics#41]
Clean temp...
segment parameters: 12.4M
netG parameters: 11.38M
Clean Mosaic: C:\Users\OneRains\Desktop\mosaic.png
--------------------ERROR--------------------
--------------Environment--------------
DeepMosaics: 0.4.0
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Pytorch: 0.4.1
OpenCV: 4.1.0
Platform: Windows-10-10.0.18362-SP0
--------------BUG--------------
Error Type: <class 'cv2.error'>
OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\filterengine.hpp:363: error: (-215:Assertion failed) anchor.inside(Rect(0, 0, ksize.width, ksize.height)) in function 'cv::normalizeAnchor'

<FrameSummary file deepmosaic.py, line 64 in <module>>
<FrameSummary file deepmosaic.py, line 40 in main>
<FrameSummary file cores\core.py, line 169 in cleanmosaic_img>
<FrameSummary file models\runmodel.py, line 75 in get_mosaic_position>
<FrameSummary file util\image_processing.py, line 201 in mask_threshold>
Please press any key to exit.

**Comment by HypoX64** [comment]
这很奇怪，看起来像是opencv的问题。请问你是使用exe运行的还是源码运行的？你的电脑中还有没有安装其他版本的opencv？当然如果能把你想要处理的图片发一下我邮箱，我将会更容易的找到问题所在。

**Comment by OneRain233** [comment]
用的exe 然后是一张有马赛克的文字图片
![Uploading mosaic.png…]()

**Comment by OneRain233** [comment]
没有其他版本

**Comment by OneRain233** [comment]
http://abcxss.bbfqc.cn/mosaic.png
图片的链接

**Comment by HypoX64** [comment]
抱歉，你的图片完全没有可能恢复啊[捂脸]。而且我暂时也没有关于文字的预训练模型。
至于出现的问题的话，我看了一下，应该是图片的长宽比过于奇葩，我会修改代码解决这个问题的。

**Comment by OneRain233** [comment]
我就试一下（这个其实是可以恢复的，因为作为ctf赛题了，但我不知道方法，就看到了这个项目）

**Comment by HypoX64** [comment]
你这种非常规律的方形马赛克可以参考https://github.com/adamian98/pulse
