### ISSUE TITLE
Space can't be in path error

### ISSUE THREAD

**Issue by Geroto** [HypoX64/DeepMosaics#49]
I still have this message: "Sorry, 'Space' can't be in path.'  any time I try to select a pretrained model. How I correct this? Thanks.

**Comment by Geroto** [comment]
Sorry, I already resolve. Just copy from google drive directory to my desktop.

**Comment by iluvcathy** [comment]
Hi, I am also having the same problem but do not know what to do.  What did Gerotocopy from google drive to their desktop to solve the problem?

**Comment by MazeMarlowe** [comment]
> Hi, I am also having the same problem but do not know what to do. What did Geroto copy from google drive to their desktop to solve the problem?

you need to remove any spaces from the folder names and file names even before the folder that houses Deep Mosaic
