### ISSUE TITLE
Recommended Hardware or Adjust Parameter for low end GPU

### ISSUE THREAD

**Issue by Engrish** [HypoX64/DeepMosaics#52]
I'm running into a CUDA out of memory error. Currently, I'm using i3-6100 with 16GB of memory and a Nvidia GTX 750 that only has 1GB of memory. Is there a way to adjust the parameter for low end GPU? If not, what's the minimum memory required for the GPU?

**Comment by HypoX64** [comment]
At least 4GB of gpu memory is required.
GTX 750 is not support, you can run it without gpu.

**Comment by Engrish** [comment]
Thanks for the update. I did try using CPU only but it took a week so I was hoping CUDA would be faster. Please kindly update the readme to include the min. 4GB requirement.
