### ISSUE TITLE
change image format

### ISSUE THREAD

**Issue by SangenBR** [HypoX64/DeepMosaics#53]
I want to change the image format from jpg to png or tiff because of the quality, how do I do this in the gui version?

**Comment by HypoX64** [comment]
You can try to add "--tempimage_type png" to the end of the displayed command.
Like this:
```bash
cd ./core&start deepmosaic.exe --mode auto --media_path C:\Users\phone\Desktop\tmp\test_media\av\test2.mp4 --model_path C:\Users\phone\Desktop\tmp\pretrained_models\mosaic\clean_youknow_video.pth --fps 0 --gpu_id 0 -ss 00:00:00 -t 00:00:00 --result_dir ../result --tempimage_type png
```

**Comment by SangenBR** [comment]
Thank you so much.
Your program to remove mosaic in JAV is even better than JavPlayer, would you like to train a model for 2D hentai? I tried with the tutorial described here but it didn't work since I don't have much knowledge.

**Comment by SangenBR** [comment]
I think the mosaic mask has to be improved since it detects a lot of things that are not mosaics and causes artifacts and also lets a lot of mosaic through

**Comment by HypoX64** [comment]
I will try to train hentai model in the future...
And, Yes, I know. Mosaic area detection Algorithm  does need to be optimized...😂

**Comment by SangenBR** [comment]
> I will try to train hentai model in the future...
> And, Yes, I know. Mosaic area detection Algorithm does need to be optimized...😂

Oh, Thx
