### ISSUE TITLE
[问题咨询]请问训练pix2pixHD是干什么用的？跟add/train和clean/train有什么区别和联系？

### ISSUE THREAD

**Issue by CaptainEven** [HypoX64/DeepMosaics#55]

**Comment by CaptainEven** [comment]
如何测试pix2pixHD(clean)的训练模型？

**Comment by HypoX64** [comment]
我已经在这里大致描述了一下整个流程
https://github.com/HypoX64/DeepMosaics/blob/master/docs/training_with_your_own_dataset.md
其实原理就是首先要获得一个能够自动识别需要打马赛克部位的模型，然后通过通过原始图片生成打马赛克的图片，这样同一对有码和无码的图片就可以训练pix2pixHD了，视频类似，但是对模型我进行了非常大的改动。

**Comment by HypoX64** [comment]
pix2pixHD的具体使用方法参见：
https://github.com/NVIDIA/pix2pixHD

**Comment by CaptainEven** [comment]
@HypoX64 多谢回复！

**Comment by FrankLinxzx** [comment]
> 我已经在这里大致描述了一下整个流程
> https://github.com/HypoX64/DeepMosaics/blob/master/docs/training_with_your_own_dataset.md
> 其实原理就是首先要获得一个能够自动识别需要打马赛克部位的模型，然后通过通过原始图片生成打马赛克的图片，这样同一对有码和无码的图片就可以训练pix2pixHD了，视频类似，但是对模型我进行了非常大的改动。

請問下 加入馬賽克  的原圖 有大小限制嗎 
--loadsize 512 --finesize 360  這兩個分別是什麼意思  謝謝您
