### ISSUE TITLE
[Type of Generator error!] Test error occur when testing model trained with pix2pixHD

### ISSUE THREAD

**Issue by CaptainEven** [HypoX64/DeepMosaics#56]
Type of Generator error!
Please press any key to exit.

If set --netG to be HD, the error is as follows:
segment parameters: 12.4M
--------------------ERROR--------------------
--------------Environment--------------
DeepMosaics: 0.5.0
Python: 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
Pytorch: 1.6.0
OpenCV: 4.5.1
Platform: Linux-5.4.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
--------------BUG--------------
Error Type: <class 'RuntimeError'>
Error(s) in loading state_dict for BiSeNet:
	Missing key(s) in state_dict: "saptial_path.convblock1.conv1.weight", "saptial_path.convblock1.bn.weight", "saptial_path.convblock1.bn.bias", "saptial_path.convblock1.bn.running_mean", "saptial_path.convblock1.bn.running_var", "saptial_path.convblock2.conv1.weight", "saptial_path.convblock2.bn.weight", "saptial_path.convblock2.bn.bias", "saptial_path.convblock2.bn.running_mean", "saptial_path.convblock2.bn.running_var", "saptial_path.convblock3.conv1.weight", "saptial_path.convblock3.bn.weight", "saptial_path.convblock3.bn.bias", "saptial_path.convblock3.bn.running_mean", "saptial_path.convblock3.bn.running_var", "context_path.features.conv1.weight", "context_path.features.bn1.weight", "context_path.features.bn1.bias", "context_path.features.bn1.running_mean", "context_path.features.bn1.running_var", "context_path.features.layer1.0.conv1.weight", "context_path.features.layer1.0.bn1.weight", "context_path.features.layer1.0.bn1.bias", "context_path.features.layer1.0.bn1.running_mean", "context_path.features.layer1.0.bn1.running_var", "context_path.features.layer1.0.conv2.weight", "context_path.features.layer1.0.bn2.weight", "context_path.features.layer1.0.bn2.bias", "context_path.features.layer1.0.bn2.running_mean", "context_path.features.layer1.0.bn2.running_var", "context_path.features.layer1.1.conv1.weight", "context_path.features.layer1.1.bn1.weight", "context_path.features.layer1.1.bn1.bias", "context_path.features.layer1.1.bn1.running_mean", "context_path.features.layer1.1.bn1.running_var", "context_path.features.layer1.1.conv2.weight", "context_path.features.layer1.1.bn2.weight", "context_path.features.layer1.1.bn2.bias", "context_path.features.layer1.1.bn2.running_mean", "context_path.features.layer1.1.bn2.running_var", "context_path.features.layer2.0.conv1.weight", "context_path.features.layer2.0.bn1.weight", "context_path.features.layer2.0.bn1.bias", "context_path.features.layer2.0.bn1.running_mean", "context_path.features.layer2.0.bn1.running_var", "context_path.features.layer2.0.conv2.weight", "context_path.features.layer2.0.bn2.weight", "context_path.features.layer2.0.bn2.bias", "context_path.features.layer2.0.bn2.running_mean", "context_path.features.layer2.0.bn2.running_var", "context_path.features.layer2.0.downsample.0.weight", "context_path.features.layer2.0.downsample.1.weight", "context_path.features.layer2.0.downsample.1.bias", "context_path.features.layer2.0.downsample.1.running_mean", "context_path.features.layer2.0.downsample.1.running_var", "context_path.features.layer2.1.conv1.weight", "context_path.features.layer2.1.bn1.weight", "context_path.features.layer2.1.bn1.bias", "context_path.features.layer2.1.bn1.running_mean", "context_path.features.layer2.1.bn1.running_var", "context_path.features.layer2.1.conv2.weight", "context_path.features.layer2.1.bn2.weight", "context_path.features.layer2.1.bn2.bias", "context_path.features.layer2.1.bn2.running_mean", "context_path.features.layer2.1.bn2.running_var", "context_path.features.layer3.0.conv1.weight", "context_path.features.layer3.0.bn1.weight", "context_path.features.layer3.0.bn1.bias", "context_path.features.layer3.0.bn1.running_mean", "context_path.features.layer3.0.bn1.running_var", "context_path.features.layer3.0.conv2.weight", "context_path.features.layer3.0.bn2.weight", "context_path.features.layer3.0.bn2.bias", "context_path.features.layer3.0.bn2.running_mean", "context_path.features.layer3.0.bn2.running_var", "context_path.features.layer3.0.downsample.0.weight", "context_path.features.layer3.0.downsample.1.weight", "context_path.features.layer3.0.downsample.1.bias", "context_path.features.layer3.0.downsample.1.running_mean", "context_path.features.layer3.0.downsample.1.running_var", "context_path.features.layer3.1.conv1.weight", "context_path.features.layer3.1.bn1.weight", "context_path.features.layer3.1.bn1.bias", "context_path.features.layer3.1.bn1.running_mean", "context_path.features.layer3.1.bn1.running_var", "context_path.features.layer3.1.conv2.weight", "context_path.features.layer3.1.bn2.weight", "context_path.features.layer3.1.bn2.bias", "context_path.features.layer3.1.bn2.running_mean", "context_path.features.layer3.1.bn2.running_var", "context_path.features.layer4.0.conv1.weight", "context_path.features.layer4.0.bn1.weight", "context_path.features.layer4.0.bn1.bias", "context_path.features.layer4.0.bn1.running_mean", "context_path.features.layer4.0.bn1.running_var", "context_path.features.layer4.0.conv2.weight", "context_path.features.layer4.0.bn2.weight", "context_path.features.layer4.0.bn2.bias", "context_path.features.layer4.0.bn2.running_mean", "context_path.features.layer4.0.bn2.running_var", "context_path.features.layer4.0.downsample.0.weight", "context_path.features.layer4.0.downsample.1.weight", "context_path.features.layer4.0.downsample.1.bias", "context_path.features.layer4.0.downsample.1.running_mean", "context_path.features.layer4.0.downsample.1.running_var", "context_path.features.layer4.1.conv1.weight", "context_path.features.layer4.1.bn1.weight", "context_path.features.layer4.1.bn1.bias", "context_path.features.layer4.1.bn1.running_mean", "context_path.features.layer4.1.bn1.running_var", "context_path.features.layer4.1.conv2.weight", "context_path.features.layer4.1.bn2.weight", "context_path.features.layer4.1.bn2.bias", "context_path.features.layer4.1.bn2.running_mean", "context_path.features.layer4.1.bn2.running_var", "context_path.features.fc.weight", "context_path.features.fc.bias", "context_path.conv1.weight", "context_path.bn1.weight", "context_path.bn1.bias", "context_path.bn1.running_mean", "context_path.bn1.running_var", "context_path.layer1.0.conv1.weight", "context_path.layer1.0.bn1.weight", "context_path.layer1.0.bn1.bias", "context_path.layer1.0.bn1.running_mean", "context_path.layer1.0.bn1.running_var", "context_path.layer1.0.conv2.weight", "context_path.layer1.0.bn2.weight", "context_path.layer1.0.bn2.bias", "context_path.layer1.0.bn2.running_mean", "context_path.layer1.0.bn2.running_var", "context_path.layer1.1.conv1.weight", "context_path.layer1.1.bn1.weight", "context_path.layer1.1.bn1.bias", "context_path.layer1.1.bn1.running_mean", "context_path.layer1.1.bn1.running_var", "context_path.layer1.1.conv2.weight", "context_path.layer1.1.bn2.weight", "context_path.layer1.1.bn2.bias", "context_path.layer1.1.bn2.running_mean", "context_path.layer1.1.bn2.running_var", "context_path.layer2.0.conv1.weight", "context_path.layer2.0.bn1.weight", "context_path.layer2.0.bn1.bias", "context_path.layer2.0.bn1.running_mean", "context_path.layer2.0.bn1.running_var", "context_path.layer2.0.conv2.weight", "context_path.layer2.0.bn2.weight", "context_path.layer2.0.bn2.bias", "context_path.layer2.0.bn2.running_mean", "context_path.layer2.0.bn2.running_var", "context_path.layer2.0.downsample.0.weight", "context_path.layer2.0.downsample.1.weight", "context_path.layer2.0.downsample.1.bias", "context_path.layer2.0.downsample.1.running_mean", "context_path.layer2.0.downsample.1.running_var", "context_path.layer2.1.conv1.weight", "context_path.layer2.1.bn1.weight", "context_path.layer2.1.bn1.bias", "context_path.layer2.1.bn1.running_mean", "context_path.layer2.1.bn1.running_var", "context_path.layer2.1.conv2.weight", "context_path.layer2.1.bn2.weight", "context_path.layer2.1.bn2.bias", "context_path.layer2.1.bn2.running_mean", "context_path.layer2.1.bn2.running_var", "context_path.layer3.0.conv1.weight", "context_path.layer3.0.bn1.weight", "context_path.layer3.0.bn1.bias", "context_path.layer3.0.bn1.running_mean", "context_path.layer3.0.bn1.running_var", "context_path.layer3.0.conv2.weight", "context_path.layer3.0.bn2.weight", "context_path.layer3.0.bn2.bias", "context_path.layer3.0.bn2.running_mean", "context_path.layer3.0.bn2.running_var", "context_path.layer3.0.downsample.0.weight", "context_path.layer3.0.downsample.1.weight", "context_path.layer3.0.downsample.1.bias", "context_path.layer3.0.downsample.1.running_mean", "context_path.layer3.0.downsample.1.running_var", "context_path.layer3.1.conv1.weight", "context_path.layer3.1.bn1.weight", "context_path.layer3.1.bn1.bias", "context_path.layer3.1.bn1.running_mean", "context_path.layer3.1.bn1.running_var", "context_path.layer3.1.conv2.weight", "context_path.layer3.1.bn2.weight", "context_path.layer3.1.bn2.bias", "context_path.layer3.1.bn2.running_mean", "context_path.layer3.1.bn2.running_var", "context_path.layer4.0.conv1.weight", "context_path.layer4.0.bn1.weight", "context_path.layer4.0.bn1.bias", "context_path.layer4.0.bn1.running_mean", "context_path.layer4.0.bn1.running_var", "context_path.layer4.0.conv2.weight", "context_path.layer4.0.bn2.weight", "context_path.layer4.0.bn2.bias", "context_path.layer4.0.bn2.running_mean", "context_path.layer4.0.bn2.running_var", "context_path.layer4.0.downsample.0.weight", "context_path.layer4.0.downsample.1.weight", "context_path.layer4.0.downsample.1.bias", "context_path.layer4.0.downsample.1.running_mean", "context_path.layer4.0.downsample.1.running_var", "context_path.layer4.1.conv1.weight", "context_path.layer4.1.bn1.weight", "context_path.layer4.1.bn1.bias", "context_path.layer4.1.bn1.running_mean", "context_path.layer4.1.bn1.running_var", "context_path.layer4.1.conv2.weight", "context_path.layer4.1.bn2.weight", "context_path.layer4.1.bn2.bias", "context_path.layer4.1.bn2.running_mean", "context_path.layer4.1.bn2.running_var", "attention_refinement_module1.conv.weight", "attention_refinement_module1.conv.bias", "attention_refinement_module1.bn.weight", "attention_refinement_module1.bn.bias", "attention_refinement_module1.bn.running_mean", "attention_refinement_module1.bn.running_var", "attention_refinement_module2.conv.weight", "attention_refinement_module2.conv.bias", "attention_refinement_module2.bn.weight", "attention_refinement_module2.bn.bias", "attention_refinement_module2.bn.running_mean", "attention_refinement_module2.bn.running_var", "supervision1.weight", "supervision1.bias", "supervision2.weight", "supervision2.bias", "feature_fusion_module.convblock.conv1.weight", "feature_fusion_module.convblock.bn.weight", "feature_fusion_module.convblock.bn.bias", "feature_fusion_module.convblock.bn.running_mean", "feature_fusion_module.convblock.bn.running_var", "feature_fusion_module.conv1.weight", "feature_fusion_module.conv1.bias", "feature_fusion_module.conv2.weight", "feature_fusion_module.conv2.bias", "conv.weight", "conv.bias". 
	Unexpected key(s) in state_dict: "model.1.weight", "model.1.bias", "model.4.weight", "model.4.bias", "model.7.weight", "model.7.bias", "model.10.weight", "model.10.bias", "model.13.weight", "model.13.bias", "model.16.conv_block.1.weight", "model.16.conv_block.1.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.17.conv_block.1.weight", "model.17.conv_block.1.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.18.conv_block.1.weight", "model.18.conv_block.1.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.19.conv_block.1.weight", "model.19.conv_block.1.bias", "model.19.conv_block.5.weight", "model.19.conv_block.5.bias", "model.20.conv_block.1.weight", "model.20.conv_block.1.bias", "model.20.conv_block.5.weight", "model.20.conv_block.5.bias", "model.21.conv_block.1.weight", "model.21.conv_block.1.bias", "model.21.conv_block.5.weight", "model.21.conv_block.5.bias", "model.22.conv_block.1.weight", "model.22.conv_block.1.bias", "model.22.conv_block.5.weight", "model.22.conv_block.5.bias", "model.23.conv_block.1.weight", "model.23.conv_block.1.bias", "model.23.conv_block.5.weight", "model.23.conv_block.5.bias", "model.24.conv_block.1.weight", "model.24.conv_block.1.bias", "model.24.conv_block.5.weight", "model.24.conv_block.5.bias", "model.25.weight", "model.25.bias", "model.28.weight", "model.28.bias", "model.31.weight", "model.31.bias", "model.34.weight", "model.34.bias", "model.38.weight", "model.38.bias". 
<FrameSummary file /mnt/diskc/even/DeepMosaic/deepmosaic.py, line 81 in <module>>
<FrameSummary file /mnt/diskc/even/DeepMosaic/deepmosaic.py, line 40 in run>
<FrameSummary file /mnt/diskc/even/DeepMosaic/models/loadmodel.py, line 86 in bisenet>
<FrameSummary file /home/jaya/.local/lib/python3.7/site-packages/torch/nn/modules/module.py, line 1045 in load_state_dict>
Please press any key to exit.

**Comment by HypoX64** [comment]
Generally, --netG will be automatically identified according to the name of the model, and it may be incompatible if you set it.

**Comment by CaptainEven** [comment]
@HypoX64 Got it!
